# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\python\pyqt5-test\ui\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(648, 678)
        MainWindow.setIconSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 40, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.temp = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.temp.setAlignment(QtCore.Qt.AlignCenter)
        self.temp.setObjectName("temp")
        self.verticalLayout.addWidget(self.temp)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(370, 40, 160, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.hum = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.hum.setAlignment(QtCore.Qt.AlignCenter)
        self.hum.setObjectName("hum")
        self.verticalLayout_2.addWidget(self.hum)
        self.temp_view = QChartView(self.centralwidget)
        self.temp_view.setGeometry(QtCore.QRect(140, 140, 391, 231))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(6)
        self.temp_view.setFont(font)
        self.temp_view.setInteractive(False)
        self.temp_view.setObjectName("temp_view")
        self.hum_view = QChartView(self.centralwidget)
        self.hum_view.setGeometry(QtCore.QRect(140, 380, 391, 231))
        font = QtGui.QFont()
        font.setFamily("AcadEref")
        font.setPointSize(6)
        self.hum_view.setFont(font)
        self.hum_view.setInteractive(True)
        self.hum_view.setObjectName("hum_view")
        self.temp_btn = QtWidgets.QPushButton(self.centralwidget)
        self.temp_btn.setGeometry(QtCore.QRect(60, 40, 81, 81))
        self.temp_btn.setObjectName("temp_btn")
        self.hum_btn = QtWidgets.QPushButton(self.centralwidget)
        self.hum_btn.setGeometry(QtCore.QRect(530, 40, 81, 81))
        self.hum_btn.setObjectName("hum_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 648, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "温度"))
        self.temp.setText(_translate("MainWindow", "24.6℃"))
        self.label_3.setText(_translate("MainWindow", "湿度"))
        self.hum.setText(_translate("MainWindow", "65.1%"))
        self.temp_btn.setText(_translate("MainWindow", "导出Excel"))
        self.hum_btn.setText(_translate("MainWindow", "导出Excel"))
from PyQt5.QtChart import QChartView
import pic_rc
